CREATE TABLE `o-ring`.`rawMaterials` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    materialItem VARCHAR(255),
    supplier VARCHAR(255),
    currentQuantity INT,
    thresholdQuantity INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );
  
  CREATE TABLE `o-ring`.`mixing` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    batchNo VARCHAR(255),
    batchCode VARCHAR(255),
    item VARCHAR(255),
    party VARCHAR(255),
    jobType VARCHAR(255),
    totalKgs INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );
  
  CREATE TABLE `o-ring`.`mixture` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    batchCode VARCHAR(255),
    chemicalMixture VARCHAR(255),
    quantity VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );
  
  CREATE TABLE `o-ring`.`tools` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    materialItem VARCHAR(255),
    currentQuantity INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );
  
  CREATE TABLE `o-ring`.`faq` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    faqQuestion TEXT,
    faqAnswer TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );